INSERT INTO `state` (`id`, `name`) VALUES
(1,'Bayern'),
(2,'Baden-Württemberg'),
(3,'Rheinland-Pfalz'),
(4,'Mecklenburg-Vorpommern'),
(5,'Sachsen-Anhalt'),
(6,'Brandenburg'),
(7,'Niedersachsen'),
(8,'Schleswig-Holstein'),
(9,'Nordrhein-Westfalen'),
(10,'Thüringen'),
(11,'Hessen'),
(12,'Sachsen'),
(13,'Berlin'),
(14,'Saarland'),
(15,'Bremen'),
(16,'Hamburg');